### ISSUE TITLE
  Generate Label Uncertainty with GLEnet:  I reported an error when running step1.1:

### ISSUE THREAD

**Issue by 6Superman6** [Eaphan/GLENet#3]
Generate Label Uncertainty with GLEnet:

I reported an error when running step1.1:

2023-02-17 10:37:27,087   INFO  **********************Start training /exp20_gen(fold_0)**********************
epochs:   0%|                                           | 0/400 [00:05<?, ?it/s]
Traceback (most recent call last):                      | 0/111 [00:00<?, ?it/s]
  File "train.py", line 247, in <module>
    main()
  File "train.py", line 202, in main
    train_model(
  File "/home/dell/project/pcdet/GLENet-main/cvae_uncertainty/train_utils/train_utils.py", line 119, in train_model
    accumulated_iter = train_one_epoch(
  File "/home/dell/project/pcdet/GLENet-main/cvae_uncertainty/train_utils/train_utils.py", line 70, in train_one_epoch
    loss.backward()
  File "/home/dell/anaconda3/envs/glenet/lib/python3.8/site-packages/torch/tensor.py", line 245, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/home/dell/anaconda3/envs/glenet/lib/python3.8/site-packages/torch/autograd/__init__.py", line 145, in backward
    Variable._execution_engine.run_backward(
RuntimeError: CUDA error: CUBLAS_STATUS_EXECUTION_FAILED when calling `cublasSgemm( handle, opa, opb, m, n, k, &alpha, a, lda, b, ldb, &beta, c, ldc)`
Traceback (most recent call last):                                              
  File "train.py", line 247, in <module>                                        
    main()
  File "train.py", line 202, in main
    train_model(
  File "/home/dell/project/pcdet/GLENet-main/cvae_uncertainty/train_utils/train_utils.py", line 119, in train_model
    accumulated_iter = train_one_epoch(
  File "/home/dell/project/pcdet/GLENet-main/cvae_uncertainty/train_utils/train_utils.py", line 70, in train_one_epoch
    loss.backward()
  File "/home/dell/anaconda3/envs/glenet/lib/python3.8/site-packages/torch/tensor.py", line 245, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/home/dell/anaconda3/envs/glenet/lib/python3.8/site-packages/torch/autograd/__init__.py", line 145, in backward
    Variable._execution_engine.run_backward(
RuntimeError: CUDA error: CUBLAS_STATUS_EXECUTION_FAILED when calling `cublasSgemm( handle, opa, opb, m, n, k, &alpha, a, lda, b, ldb, &beta, c, ldc)`
Killing subprocess 3121397
Killing subprocess 3121398
Traceback (most recent call last):
  File "/home/dell/anaconda3/envs/glenet/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/dell/anaconda3/envs/glenet/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/dell/anaconda3/envs/glenet/lib/python3.8/site-packages/torch/distributed/launch.py", line 340, in <module>
    main()
  File "/home/dell/anaconda3/envs/glenet/lib/python3.8/site-packages/torch/distributed/launch.py", line 326, in main
    sigkill_handler(signal.SIGTERM, None)  # not coming back
  File "/home/dell/anaconda3/envs/glenet/lib/python3.8/site-packages/torch/distributed/launch.py", line 301, in sigkill_handler
    raise subprocess.CalledProcessError(returncode=last_return_code, cmd=cmd)
subprocess.CalledProcessError: Command '['/home/dell/anaconda3/envs/glenet/bin/python', '-u', 'train.py', '--local_rank=1', '--launcher', 'pytorch', '--cfg_file', 'cfgs/exp20_gen.yaml', '--tcp_port', '18889', '--max_ckpt_save_num', '10', '--workers', '1', '--extra_tag', 'fold_0']' returned non-zero exit status 1.

**Comment by Eaphan** [comment]
1. Do you have two GPUs on your machine? Note I use two GPUs for training the GLENet. If you only have only one GPU, you should change the command adaptively.
2. Have you installed the right version Pytorch? Can your train other models on your server?

**Comment by 6Superman6** [comment]
My computer has two GPUs, which can train other models. There is also a missing file when executing step 1.1: cfgs/${exp_id}_ gen_ ori.yaml

**Comment by Eaphan** [comment]
Sorry, I have fixed the bug. The cfgs/exp20_gen.yaml should be cfgs/exp20_gen_ori.yaml. 

I have just fixed some bugs and run off the process. You can pull the lastest change and try again. @6Superman6

**Comment by 6Superman6** [comment]
> 



> Sorry, I have fixed the bug. The cfgs/exp20_gen.yaml should be cfgs/exp20_gen_ori.yaml.
> 
> I have just fixed some bugs and run off the process. You can pull the lastest change and try again. @6Superman6

**Step 1.1 can now be executed successfully, but the following error is reported when executing step 1.2:**

2023-02-17 16:31:31,845   INFO  cfg.TAG: exp20_gen
2023-02-17 16:31:31,845   INFO  cfg.EXP_GROUP_PATH: 
2023-02-17 16:31:32,016   INFO  Length of dense_gt_infos is 156
2023-02-17 16:31:32,016   INFO  ### Aug params: flip=True, scale=[0.95, 1.05], rot=0.78539816,shift=0, enable_similar_type=True
Traceback (most recent call last):
  File "test.py", line 203, in <module>
    main()
  File "test.py", line 199, in main
    eval_single_ckpt(model, test_loader, args, eval_output_dir, logger, epoch_id, dist_test=dist_test)
  File "test.py", line 59, in eval_single_ckpt
    model.load_params_from_file(filename=args.ckpt, logger=logger, to_cpu=dist_test)
  File "/home/dell/project/pcdet/GLENet-main/cvae_uncertainty/model.py", line 371, in load_params_from_file
    raise FileNotFoundError
FileNotFoundError

**Comment by Eaphan** [comment]
Please make sure you execute step 1.1 successfully. You can check whether the checkpoints are well saved in each directory like fold_*.

**Comment by 6Superman6** [comment]
> 

Sorry, I didn't succeed in step 1.1 training just now. Now I can train normally. After the step 1.1 training is completed, I believe that step 1.2 should be able to run normally.

**Comment by 6Superman6** [comment]
> Please make sure you execute step 1.1 successfully. You can check whether the checkpoints are well saved in each directory like fold_*.

Sorry, I didn't succeed in step 1.1 training just now. Now I can train normally. After the step 1.1 training is completed, I believe that step 1.2 should be able to run normally.  @Eaphan

**Comment by 6Superman6** [comment]
Thank you very much. Now step1.0-step1.3 can be successfully executed. @Eaphan

**Comment by mishimat34** [comment]
@Eaphan @6Superman6 
I too have the same issues. Need your kind help.
Although I can use kitti_infos_train.pkl & kitti_dbinfos_train.pkl offered by @Eaphan but I want to study and tune model.py in cvae_uncertainty so that I must generate kitti_infos_train.pkl & kitti_dbinfos_train.pkl of my own.

1. I run ln -s data/kitti cvae_uncertainty, which doesn't work. So when running step 1.2: GLENet Prediction I have:

 Traceback (most recent call last):
  File "test.py", line 203, in <module>
    main()
  File "test.py", line 189, in main
    dist=dist_test, workers=args.workers, logger=logger, training=False
  File "/home/lab715/Code/GLENet/cvae_uncertainty/dataset.py", line 1047, in build_dataloader
    logger=logger,
  File "/home/lab715/Code/GLENet/cvae_uncertainty/dataset.py", line 136, in __init__
    with open(db_infos_path, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'kitti/kitti_dbinfos_train.pkl'

So I guessed and moved kitti/kitti_dbinfos_train.pkl into cvae_uncertainty/kitti (I built kitti under cvae_uncertainty).

2. Running step 1.2 again then I have:

Traceback (most recent call last):
  File "test.py", line 203, in <module>
    main()
  File "test.py", line 199, in main
    eval_single_ckpt(model, test_loader, args, eval_output_dir, logger, epoch_id, dist_test=dist_test)
  File "test.py", line 59, in eval_single_ckpt
    model.load_params_from_file(filename=args.ckpt, logger=logger, to_cpu=dist_test)
  File "/home/lab715/Code/GLENet/cvae_uncertainty/model.py", line 371, in load_params_from_file
    raise FileNotFoundError

3. Seems I don't have training results in cvae_uncertainty/output/exp20_gen/fold_x/ckpt, so step 1.1 would be that for me:
    FOLD_IDX: 0
    FOLD_IDX: 1
    FOLD_IDX: 2
    FOLD_IDX: 3
    FOLD_IDX: 4
    FOLD_IDX: 5
    FOLD_IDX: 6
    FOLD_IDX: 7
    FOLD_IDX: 8
    FOLD_IDX: 9

How can I do to have the training results in fold_x/ckpt?
Thanks.

**Comment by Eaphan** [comment]
ln -s data/kitti cvae_uncertainty, which doesn't work
>>
Why doesn't it work? Do you prepare the data of KITTI and create the directory well?

**Comment by lhsgwyz** [comment]
> 我也有同样的问题。需要你的帮助。虽然我可以使用kitti_infos_train.pkl & kitti_dbinfos_train.pkl提供的，但我想在cvae_uncertainty中学习和调整 model.py，以便我必须生成我自己的kitti_infos_train.pkl &kitti_dbinfos_train.pkl。
> 
> 1. 我运行 ln -s data/kitti cvae_uncertainty，它不起作用。因此，在运行步骤 1.2：GLENet 预测时，我有：
> 
> 回溯（最近一次调用）：文件“test.py”，第 203 行，在 main（） 文件“test.py”，第 189 行，在 main dist=dist_test，workers=args.workers，logger=logger，training=False 文件“/home/lab715/Code/GLENet/cvae_uncertainty/dataset.py”，第 1047 行，在 build_dataloader logger=logger，文件“/home/lab715/Code/GLENet/cvae_uncertainty/dataset.py”，第 136 行，**init** with open（db_infos_path， 'rb'） as f： FileNotFoundError： [Errno 2] 没有这样的文件或目录： 'kitti/kitti_dbinfos_train.pkl'
> 
> 所以我猜测并将 kitti/kitti_dbinfos_train.pkl 移动到 cvae_uncertainty/kitti 中（我在 cvae_uncertainty 下构建了 kitti）。
> 
> 2. 再次运行步骤 1.2，然后我有：
> 
> 回溯（最近一次调用最后一次）：文件“test.py”，第 203 行，在 main（） 文件“test.py”，第 199 行，在 main eval_single_ckpt（model， test_loader， args， eval_output_dir， logger， epoch_id， dist_test=dist_test） 文件“test.py”，第 59 行，在 eval_single_ckpt model.load_params_from_file（filename=args.ckpt， logger=logger， to_cpu=dist_test）文件“/home/lab715/Code/GLENet/cvae_uncertainty/model.py”，第 371 行，load_params_from_file引发 FileNotFoundError
> 
> 3. 似乎我没有 cvae_uncertainty/output/exp20_gen/fold_x/ckpt 的训练结果，所以步骤 1.1 对我来说就是这样： FOLD_IDX：0 FOLD_IDX：1 FOLD_IDX：2 FOLD_IDX：3 FOLD_IDX：4 FOLD_IDX：5 FOLD_IDX：6 FOLD_IDX：7 FOLD_IDX：8 FOLD_IDX：9
> 
> 我怎样才能获得 fold_x/ckpt 的训练结果？ 谢谢。



> @Eaphan @6Superman6 I too have the same issues. Need your kind help. Although I can use kitti_infos_train.pkl & kitti_dbinfos_train.pkl offered by @Eaphan but I want to study and tune model.py in cvae_uncertainty so that I must generate kitti_infos_train.pkl & kitti_dbinfos_train.pkl of my own.
> 
> 1. I run ln -s data/kitti cvae_uncertainty, which doesn't work. So when running step 1.2: GLENet Prediction I have:
> 
> Traceback (most recent call last): File "test.py", line 203, in main() File "test.py", line 189, in main dist=dist_test, workers=args.workers, logger=logger, training=False File "/home/lab715/Code/GLENet/cvae_uncertainty/dataset.py", line 1047, in build_dataloader logger=logger, File "/home/lab715/Code/GLENet/cvae_uncertainty/dataset.py", line 136, in **init** with open(db_infos_path, 'rb') as f: FileNotFoundError: [Errno 2] No such file or directory: 'kitti/kitti_dbinfos_train.pkl'
> 
> So I guessed and moved kitti/kitti_dbinfos_train.pkl into cvae_uncertainty/kitti (I built kitti under cvae_uncertainty).
> 
> 2. Running step 1.2 again then I have:
> 
> Traceback (most recent call last): File "test.py", line 203, in main() File "test.py", line 199, in main eval_single_ckpt(model, test_loader, args, eval_output_dir, logger, epoch_id, dist_test=dist_test) File "test.py", line 59, in eval_single_ckpt model.load_params_from_file(filename=args.ckpt, logger=logger, to_cpu=dist_test) File "/home/lab715/Code/GLENet/cvae_uncertainty/model.py", line 371, in load_params_from_file raise FileNotFoundError
> 
> 3. Seems I don't have training results in cvae_uncertainty/output/exp20_gen/fold_x/ckpt, so step 1.1 would be that for me:
>    FOLD_IDX: 0
>    FOLD_IDX: 1
>    FOLD_IDX: 2
>    FOLD_IDX: 3
>    FOLD_IDX: 4
>    FOLD_IDX: 5
>    FOLD_IDX: 6
>    FOLD_IDX: 7
>    FOLD_IDX: 8
>    FOLD_IDX: 9
> 
> How can I do to have the training results in fold_x/ckpt? Thanks.

I have the same issues as you, have you solved your problem yet?

**Comment by Eaphan** [comment]
You should complete step 1.1 before you start step 1.2.

**Comment by mishimat34** [comment]
I found that i can modify label training instruction from "for iter in `seq 0 9`" to "`seq 0 0`".
I can train with only FOLD_IDX 0，but still can't generate the uncertainty label (still lacking evaluation data from FOLD_IDX 1 to 9) 
FOLD_IDX 0 and FOLD_IDX 9, are they corresponding to different parts of KITTI, respectively?
Should I train the label uncertainty with entire FOLD_IDX 0 to 9?


我發現可以透過指令修改 for iter in `seq 0 9`至 `seq 0 0`，如此只做 FOLD_IDX: 0，一樣能訓練(但資料不足無法生成標籤)。
想請問 FOLD_IDX: 0到  FOLD_IDX: 9分別對應KITTI中不同的部分與樣本嗎？
訓練標籤的時候一定要從FOLD_IDX 0 做到FOLD_IDX 9嗎?



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
24/04/09
下午08:05:16

YF Zhang ***@***.***> 於 2024年3月25日 週一 下午5:33寫道：

**Comment by mishimat34** [comment]
Updated.

I found that I can modify label training instructions from "for iter in
`seq 0 9`" to "`seq 0 0`". I can train with single FOLD_IDX 0，but still
can't generate the uncertainty label (still lacking evaluation data from
FOLD_IDX 1 to 9) FOLD_IDX 0 and FOLD_IDX 9, are they corresponding to
different parts of KITTI, respectively? Should I train the label
uncertainty with the entire FOLD_IDX 0, 1, 2, ... to 9?




[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
24/04/09
下午08:24:11

DL251陳秀吉 ***@***.***> 於 2024年4月9日 週二 下午8:08寫道：
